# Generated by Django 4.2.17 on 2024-12-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
