# Generated by Django 4.2.17 on 2025-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_news_alter_tweet_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='tweet',
            name='classification',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tweet',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
